version: '3.8'
services:
  client:
    image: node:20-alpine
    working_dir: /app/client
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

  cms:
    image: node:20-alpine
    working_dir: /app/cms
    command: sh -c "npm install && npm run develop"
    ports:
      - "1337:1337"
    volumes:
      - ./:/app
